apiVersion: v1
kind: Pod
metadata:
  name: longhorn-pod-affinity-required
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker-itp-1
            - worker-itp-2  # Can specify multiple nodes
            - master-itp-1
          # Can add more match expressions
          # - key: disktype # add if you have disktype lik ssd
          #   operator: In
          #   values:
          #   - ssd
  containers:
    - name: test-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: test-vol
          mountPath: /data
  volumes:
    - name: test-vol
      persistentVolumeClaim:
        claimName: longhorn-pvc-test