apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn   # make sure this matches your default Longhorn SC
