[all:vars]
ansible_user=window
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[local]
localhost ansible_connection=local

[masters]
master01 ansible_host=34.84.181.61
master02 ansible_host=35.244.40.133
worker01 ansible_host=34.22.93.174
worker02 ansible_host=34.129.8.124
worker03 ansible_host=34.126.203.159
